#!/usr/bin/env ruby
require 'webrick'

port = ENV['PORT'] || '3000'
root = ENV['ROOT'] || Dir.pwd

server = WEBrick::HTTPServer.new :Port => port, :DocumentRoot => root
trap 'INT' do server.shutdown end
server.start
